### ISSUE TITLE
Connection closed error

### ISSUE THREAD

**Issue by dr3s** [kamon-io/kamon-newrelic#10]

**Comment by dr3s** [comment]
Can't seem to get anything to upload to newrelic.  The license key has been removed but is correct.

> [WARN] [08/01/2017 12:22:57.718] [kamon-akka.actor.default-dispatcher-10] [akka://kamon/user/IO-HTTP/host-connector-1/2] ErrorClosed(Connection reset by peer) in response to POST request to /agent_listener/invoke_raw_method?method=metric_data&run_id=1867514189&license_key={secret}&marshal_format=json&protocol_version=12 with no retries left, dispatching error...
> [ERROR] [08/01/2017 12:22:57.718] [kamon-akka.actor.default-dispatcher-10] [akka://kamon/user/newrelic-agent/metric-reporter] Metric POST to the New Relic collector failed, metrics will be accumulated with the next tick.
> spray.can.Http$ConnectionException: ErrorClosed(Connection reset by peer)
> 	at spray.can.client.HttpHostConnectionSlot.reportDisconnection(HttpHostConnectionSlot.scala:228)
> 	at spray.can.client.HttpHostConnectionSlot$$anonfun$connected$1.applyOrElse(HttpHostConnectionSlot.scala:161)
> 	at akka.actor.Actor$class.aroundReceive(Actor.scala:502)
> 	at spray.can.client.HttpHostConnectionSlot.aroundReceive(HttpHostConnectionSlot.scala:33)
> 	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
> 	at akka.actor.ActorCell.invoke_aroundBody0(ActorCell.scala:495)
> 	at akka.actor.ActorCell$AjcClosure1.run(ActorCell.scala:1)
> 	at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
> 	at akka.kamon.instrumentation.ActorMonitors$$anon$1$$anonfun$processMessage$1.apply(ActorMonitor.scala:63)
> 	at kamon.trace.Tracer$.withContext(TracerModule.scala:58)
> 	at akka.kamon.instrumentation.ActorMonitors$$anon$1.processMessage(ActorMonitor.scala:62)
> 	at akka.kamon.instrumentation.ActorCellInstrumentation.aroundBehaviourInvoke(ActorInstrumentation.scala:45)
> 	at akka.actor.ActorCell.invoke(ActorCell.scala:488)
> 	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
> 	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
> 	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
> 	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
> 	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
> 	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
> 	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

**Comment by dr3s** [comment]
no idea what that was but metrics are POSTing
