### ISSUE TITLE
Metric POST to the New Relic collector failed

### ISSUE THREAD

**Issue by yqset** [kamon-io/kamon-newrelic#5]
```
[ERROR] [03/15/2017 14:18:35.992] [kamon-akka.actor.default-dispatcher-2] [akka://kamon/user/newrelic-agent/metric-reporter] Metric POST to the New Relic collector failed, metrics will be accumulated with the next tick.
spray.httpx.PipelineException: UnsupportedContentType(Expected 'application/json' or 'text/plain')
    at spray.httpx.ResponseTransformation$$anonfun$unmarshal$1.apply(ResponseTransformation.scala:37)
    at spray.httpx.ResponseTransformation$$anonfun$unmarshal$1.apply(ResponseTransformation.scala:31)
    at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
    at scala.util.Try$.apply(Try.scala:192)
    at scala.util.Success.map(Try.scala:237)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
    at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:235)
    at scala.concurrent.impl.CallbackRunnable.run_aroundBody0(Promise.scala:32)
    at scala.concurrent.impl.CallbackRunnable$AjcClosure1.run(Promise.scala:1)
    at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
    at kamon.scala.instrumentation.FutureInstrumentation$$anonfun$aroundExecution$1.apply(FutureInstrumentation.scala:45)
    at kamon.trace.Tracer$.withContext(TracerModule.scala:58)
    at kamon.scala.instrumentation.FutureInstrumentation.aroundExecution(FutureInstrumentation.scala:44)
    at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:31)
    at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
    at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
    at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
    at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
    at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
    at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
    at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
    at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
    at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
    at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

Above error started happening without any code changes to my application. It is logged once per application instance per minute. I am guessing that is the interval kamon-newrelic sends data to Newrelic.

Did some digging in `kamon-newrelic` code base and these lines of code may be related?
```
val baseQuery = Query(runID.map(ri ⇒ Map("run_id" -> String.valueOf(ri))).getOrElse(Map.empty[String, String]) +
    ("license_key" -> agentSettings.licenseKey) +
    ("marshal_format" -> "json") +
    ("protocol_version" -> "12"))

  // New Relic responses contain JSON but with text/plain content type :(.
  implicit val JsValueUnmarshaller = Unmarshaller[JsValue](MediaTypes.`application/json`, MediaTypes.`text/plain`) {
    case x: HttpEntity.NonEmpty ⇒
      JsonParser(x.asString(defaultCharset = HttpCharsets.`UTF-8`))
  }
```
found in `Kamon/kamon-newrelic/src/main/scala/kamon/newrelic/ApiMethodClient.scala`.
Interesting part:
```
// New Relic responses contain JSON but with text/plain content type :(.
```

On top of that, whenever I restart my application, it will work Ok for roughly 1 hour~ before starting to error again. Any thoughts anyone?

Versions:
```
* Scala 2.11.7
* Akka 2.3.11
* Spray 1.3.3
* Kamon 0.6.3
```

**Comment by dpsoft** [comment]
Please take a look:https://github.com/kamon-io/kamon-newrelic/issues/3

**Comment by yqset** [comment]
Ah. Thank you. :)
