### ISSUE TITLE
UnsupportedClassVersionError

### ISSUE THREAD

**Issue by yqset** [kamon-io/kamon-newrelic#6]
Using
```
java version "1.7.0_95"
scala version 2.11.7
akkaV 2.3.11
sprayV 1.3.3
kamonV 0.6.3
```

```
[error] Exception in thread "main" java.lang.UnsupportedClassVersionError: kamon/util/GlobPathFilter : Unsupported major.minor version 52.0
[error] 	at java.lang.ClassLoader.defineClass1(Native Method)
[error] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
[error] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[error] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
[error] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
[error] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
[error] 	at java.security.AccessController.doPrivileged(Native Method)
[error] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
[error] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
[error] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
[error] 	at kamon.metric.MetricsSettings$$anonfun$loadFilters$1$$anonfun$1.apply(MetricsSettings.scala:99)
[error] 	at kamon.metric.MetricsSettings$$anonfun$loadFilters$1$$anonfun$1.apply(MetricsSettings.scala:98)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.Iterator$class.foreach(Iterator.scala:893)
[error] 	at scala.collection.AbstractIterator.foreach(Iterator.scala:1336)
[error] 	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
[error] 	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
[error] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
[error] 	at kamon.metric.MetricsSettings$$anonfun$loadFilters$1.apply(MetricsSettings.scala:98)
[error] 	at kamon.metric.MetricsSettings$$anonfun$loadFilters$1.apply(MetricsSettings.scala:96)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
[error] 	at scala.collection.immutable.Set$Set4.foreach(Set.scala:200)
[error] 	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
[error] 	at scala.collection.AbstractSet.scala$collection$SetLike$$super$map(Set.scala:47)
[error] 	at scala.collection.SetLike$class.map(SetLike.scala:92)
[error] 	at scala.collection.AbstractSet.map(Set.scala:47)
[error] 	at kamon.metric.MetricsSettings$.loadFilters(MetricsSettings.scala:96)
[error] 	at kamon.metric.MetricsSettings$.apply(MetricsSettings.scala:63)
[error] 	at kamon.metric.MetricsModuleImpl.<init>(MetricsModule.scala:237)
[error] 	at kamon.metric.MetricsModuleImpl$.apply(MetricsModule.scala:374)
[error] 	at kamon.Kamon$Instance.<init>(Kamon.scala:55)
[error] 	at kamon.Kamon$.<init>(Kamon.scala:30)
[error] 	at kamon.Kamon$.<clinit>(Kamon.scala)
[error] 	at com.realself.charon.application.CharonApplication.<init>(CharonApplication.scala:17)
[error] 	at com.realself.charon.application.DaemonApplication.application(ApplicationEntries.scala:26)
[error] 	at com.realself.charon.application.DaemonApplication.start(ApplicationEntries.scala:30)
[error] 	at com.realself.charon.application.CharonServer$.delayedEndpoint$com$realself$charon$application$CharonServer$1(ApplicationEntries.scala:60)
[error] 	at com.realself.charon.application.CharonServer$delayedInit$body.apply(ApplicationEntries.scala:40)
[error] 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
[error] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
[error] 	at scala.collection.immutable.List.foreach(List.scala:381)
[error] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
[error] 	at scala.App$class.main(App.scala:76)
[error] 	at com.realself.charon.application.CharonServer$.main(ApplicationEntries.scala:40)
[error] 	at com.realself.charon.application.CharonServer.main(ApplicationEntries.scala)
[error] Exception in thread "Thread-1" java.lang.NoClassDefFoundError: Could not initialize class kamon.Kamon$
[error] 	at com.realself.charon.application.CharonApplication.<init>(CharonApplication.scala:17)
[error] 	at com.realself.charon.application.DaemonApplication.application(ApplicationEntries.scala:26)
[error] 	at com.realself.charon.application.DaemonApplication.stop(ApplicationEntries.scala:32)
[error] 	at com.realself.charon.application.CharonServer$.cleanup(ApplicationEntries.scala:51)
[error] 	at com.realself.charon.application.CharonServer$$anon$1.run(ApplicationEntries.scala:56)
[error] 	at java.lang.Thread.run(Thread.java:745)
```

Application is having trouble starting up with this error. It appears to be related to a change that I have made for this issue https://github.com/kamon-io/kamon-newrelic/issues/5.

I uprev `kamon-newrelic` from `0.6.3` to `0.6.7` and above error happened

**Comment by yqset** [comment]
Any updates on this?

**Comment by dpsoft** [comment]
@yqset you can try run your app with java 1.8 or above?

**Comment by jasonjkeller** [comment]
@dpsoft @ivantopo Can this issue be closed since it relates to the old New Relic Reporter that has since been replaced?
